src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from .views import DashboardView, change_theme, chart_data, login_view, otp_view, logout_view, AboutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', DashboardView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('chart-data/', chart_data, name='data'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('otp/', otp_view, name='otp'),
    path('switch/', change_theme, name='switch'),
    path('books/', include('books.urls', namespace='books')),
    path('rentals/', include('rentals.urls', namespace='rentals')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

src/rentals/urls.py
from django.urls import path
from .views import search_book_view, BookRentalView, UpdateRentalStatus, CreateNewRental, SelectRentalDownloandView

app_name = 'rentals'

urlpatterns = [
    path('', search_book_view, name='main'),
    path('<str:book_id>/', BookRentalView.as_view(), name='detail' ),
    path('new/<str:book_id>/', CreateNewRental.as_view(), name='new'),
    path('<str:book_id>/<pk>/', UpdateRentalStatus.as_view(), name='update' ),
    path('download/<str:book_id>', SelectRentalDownloandView.as_view(), name='download' ),
]

src/rentals/models.py
from django.db import models
from customers.models import Customer
from datetime import timedelta
from .choices import STATUS_CHOICES
from books.models import Book


# Create your models here.
class Rental(models.Model):
    book = models.ForeignKey(Book, on_delete = models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete = models.CASCADE)
    # field with choices
    status = models.CharField(max_length=2, choices=STATUS_CHOICES)
    rent_start_date = models.DateField(help_text = 'when the book was rented')
    rent_end_date = models.DateField(help_text='deadline', blank=True)
    return_date = models.DateField(blank=True, help_text='actual returned date', null=True)
    is_closed = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    @property
    def status_text(self):
        status = dict(STATUS_CHOICES)
        return status[self.status]
    
    def __str__(self):
        return f"{self.book.isbn} rented by {self.customer.username}"
    
    def save(self, *args, **kwargs):
        if not self.rent_end_date:
            self.rent_end_date = self.rent_start_date + timedelta(days=14)

        super().save(*args, **kwargs)

src/rentals/forms.py
import django.forms as forms
from .choices import FORMAT_CHOICES


class SearchBookForm(forms.Form):
    search = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'search by book id ...'}))

class SelectExportOptions(forms.Form):
    format = forms.ChoiceField(choices=FORMAT_CHOICES, widget=forms.RadioSelect())

src/rentals/views.py
from typing import Any
from django.shortcuts import render
from .forms import SearchBookForm, SelectExportOptions
from django.views.generic import ListView, UpdateView, CreateView, FormView
from books.models import Book
from .models import Rental
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.db.models import Q
from .choices import FORMAT_CHOICES
from .admin import RentalResource

from django.contrib import messages
from django.http import HttpResponse
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
@login_required
def search_book_view (request):
    form= SearchBookForm(request.POST or None)
    search_query = request.POST.get('search', None)
    book_ex = Book.objects.filter(Q(isbn=search_query) | Q(id=search_query)).exists()

    if search_query != None and book_ex:
        return redirect('rentals:detail', search_query)

    context = {'form': form}

    return render(request, 'rentals/main.html', context)


class BookRentalView(LoginRequiredMixin, ListView):
    model=Rental
    context_object_name = 'rentals'
    template_name = 'rentals/detail.html'
    
    def get_queryset(self):
        # Assuming you have a way to determine the current book (e.g., through URL params)
        book_id = self.kwargs['book_id']  # Example: getting book_id from URL params
        return Rental.objects.filter(Q(book__isbn=book_id) | Q(book__id=book_id))

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context= super().get_context_data(**kwargs)
        book_id = self.kwargs['book_id']
        book = Book.objects.filter(Q(isbn=book_id) | Q(id=book_id)).first()
        context['book'] = book  # Add book to context
        context['book_id'] = book_id
        return context
    
class UpdateRentalStatus(LoginRequiredMixin, UpdateView):
    model = Rental
    template_name = 'rentals/update.html'
    fields=('status',)

    def get_success_url(self) -> str:
        book_id = self.kwargs.get('book_id')
        return reverse('rentals:detail', kwargs={'book_id':book_id}) 
    
    def form_valid(self, form):
        instance = form.save(commit=False)
        if instance.status == '#1':
            instance.return_date = datetime.today().date()
            instance.is_closed = True
        instance.save()
        messages.add_message(self.request, messages.INFO, f'Status of book {instance.book_id} was successufully updated')
        return super().form_valid(form)

class CreateNewRental(LoginRequiredMixin, CreateView):
    model = Rental
    template_name = 'rentals/new.html'
    fields = ('customer',)

    def form_valid(self, form):
        instance = form.save(commit=False)
        book_id = self.kwargs.get('book_id')
        book = Book.objects.get(id=book_id)
        instance.book = book
        instance.status = '#0'
        instance.rent_start_date = datetime.now()
        return super().form_valid(form)

    def get_success_url(self):
        book_id = self.kwargs.get('book_id')  # Get book_id for the success URL
        return reverse('rentals:detail', kwargs={'book_id': book_id})
    
class SelectRentalDownloandView(LoginRequiredMixin, FormView):
    template_name = 'rentals/download.html'
    form_class  = SelectExportOptions

    def get_success_url(self):
        return self.request.path
    
    def post(self,request, **kwargs):
        formats = dict(FORMAT_CHOICES)
        format = self.request.POST.get('format')
        format = formats[format]
        book_id = self.kwargs['book_id']
        rentals = Rental.objects.filter(Q(book__isbn=book_id) | Q(book__id=book_id))
        dataset = RentalResource().export(rentals)
        if format == 'csv':
            ds=dataset.csv
        elif format == 'json':
            ds = dataset.json
        elif format == 'xls':
            ds = dataset.xls

        response =  HttpResponse(ds, content_type=format)
        response['Content-Disposition'] = f'attachment; filename=rentals.{format}'

        return response
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context= super().get_context_data(**kwargs)
        book_id = self.kwargs['book_id']
        book = Book.objects.filter(Q(isbn=book_id) | Q(id=book_id)).all()
        context['book'] = book  # Add book to context
        context['book_id'] = book_id
        return context

src/rentals/templates/rentals/detail.html
{% extends "base.html" %}
{% load get_status_text %}
{% block title %}Rental History{% endblock title %}

{% block content %}
{% include 'components/header.html' with title=book.title.title description=book.title.publisher is_go_back=True%}
<!-- ALERT MESSAGES -->
{% if messages %}
{% for message in messages %}
    {% if 'info' in message.tags %}
        {% include "components/alert.html" with is_info=True title="Success" body=message %}
    {% endif %}
{% endfor %}
{% endif %}
{% if rentals %}
<div class="overflow-x-auto"> 
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase dark:bg-gray-700 dark:text-gray-400">
            <tr class="border">
                <th scope="col" class="py-3 px-6">
                    #
                </th>
                <th scope="col" class="py-3 px-6">
                    customer
                </th>
                <th scope="col" class="py-3 px-6">
                    isbn
                </th>
                <th scope="col" class="py-3 px-6">
                    status
                </th>
                <th scope="col" class="py-3 px-6">
                    start
                </th>
                <th scope="col" class="py-3 px-6">
                    end
                </th>
                <th scope="col" class="py-3 px-6">
                    return
                </th>
                <th scope="col" class="py-3 px-6">
                    is closed
                </th>
                
            </tr>
        </thead>
        <tbody>
            {% for rental in rentals %}
            <tr class="border-b dark:bg-gray-800 dark:border-gray-700">
                <td scope="row" class="py-4 px-6 font-medium text-gray-900 dark:text-white">
                    {{forloop.counter}}
                </td>
                <td class="py-4 px-6">
                    {{rental.customer.username}}
                </td>
                <td class="py-4 px-6">
                    {{rental.book.isbn}}
                </td>
                <td class="py-4 px-6">
                    {{rental.status|get_status_text}}
                </td>
                <td class="py-4 px-6">
                    {{rental.rent_start_date}}
                </td>
                <td class="py-4 px-6">
                    {{rental.rent_end_date}}
                </td>
                <td class="py-4 px-6">
                    {% if  rental.return_date%}{{rental.return_date}}{% else %}-{% endif %}
                </td>
                <td class="py-4 px-6">
                    {% if  rental.is_closed%}
                    <i class='fa-solid fa-check text-green-500'></i>
                    {% else %}
                    <i class='fa-solid fa-x text-rose-500'></i>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class='mt-6 h-12' >
    <a href="{% url 'rentals:download' book_id %}" class='p-3 bg-sky-500 hover:bg-sky-600 rounded-lg text-white'>download</a>   
</div>
    {% else %}
No rentals for this book yet
{% endif %}
{% endblock content %}

src/rentals/templates/rentals/download.html
{% extends "base.html" %}
{% block title %}Download rentals{% endblock title %}
{% block content %}
{% include 'components/header.html' with title="Download data" description=book_id is_go_back=True%}
<form method="POST" >
    {% csrf_token %}
    {{form}}
    <button type='submit' class='px-3 py-2 text-white bg-sky-500 hover:bg-sky-600 rounded-xl mt-3'>Download</button>
</form>
{% endblock content %}

src/rentals/templates/rentals/main.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block scripts %}
    <script src='{% static "rentals/main.js" %}' defer></script>
{% endblock scripts %}

{% block title %}Search rentals{% endblock title %}
{% block content %}
<div class="flex justify-center items-center min-h-[200px] max-h-[800px] h-auto">
    <form class="w-[500px]" id="search-form" method="POST" autocomplete="off">
        {% csrf_token %}
        <label for="{{form.search.id_for_label}}" class="block text-3xl text-gray-700 dark:text-white text-center font-bold mb-2">search for books</label>
        {{form.search|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded-lg p-3 drop-shadow-xl w-full'}}
    </form>
</div>
{% endblock content %}

src/rentals/templates/rentals/new.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %} New {% endblock title %}

{% block content %}
{{book_id}}
<form method='POST' class='w-1/2'>
    {% csrf_token %}
    <div class="mb-2">
        <label for="{{form.customer.id_for_label}}" class="block font-bold text-slate-800 dark:text-slate-300"> customer</label>
        {{form.customer|add_class:"bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full"}}
    </div>
    <button type='submit' class='px-3 py-2 text-white bg-sky-500 hover:bg-sky-600 rounded-xl mt-3'>Add</button>
</form>
{% endblock content %}

src/rentals/templates/rentals/update.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block titele %}Update Status{% endblock titele %}

{% block content %}
{% include 'components/header.html' with title="Update Rental Status" description=object.book.id is_go_back=True%}
<form method='POST' class='w-1/2'>
    {% csrf_token %}
    <div class="mb-2">
        <label for="{{form.status.id_for_label}}" class="block font-bold text-slate-800 dark:text-slate-300"> status</label>
        {{form.status|add_class:"bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full"}}
    </div>
    <button type='submit' class='px-3 py-2 text-white bg-sky-500 hover:bg-sky-600 rounded-xl mt-3'>update</button>
</form>
{% endblock content %}